{
 "title": "Metric Monitoring for GE2PE",
 "description": "-Monitoring Dashboard for GE2PE task\n",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Average Input Token in 10 Mins",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(phonemizer_input_chars_sum[10m])) / avg(rate(phonemizer_input_chars_count[10m]))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "timeseries",
   "description": "Total Request to the system in 1m time-frames\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(phonemizer_requests_total[10m])) by (outcome, voice)",
     "legendFormat": "__auto"
    },
    { "legendFormat": "__auto" },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Latency ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum(rate(phonemizer_stage_latency_seconds_bucket[10m])) by (le, stage)\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(phonemizer_errors_total[10m])) by (stage)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}